function fx = fx(dq1,dq2,q2,u)
%FX
%    FX = FX(DQ1,DQ2,Q2,U)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Apr-2019 20:44:17

t2 = cos(q2);
t3 = sin(q2);
t4 = t2.^2;
t5 = t4.*3.0;
t6 = t5-6.2e1;
t7 = 1.0./t6;
t8 = dq2.^2;
t9 = t3.*t8.*(3.0./5.0e2);
t10 = dq1.*(-1.0./1.0e1)+t9+u;
fx = [t7.*t10.*-2.0e3-t2.*t3.*t7.*2.943e2;t3.*t7.*(-1.52055e3)-t2.*t7.*t10.*5.0e2];
