function out1 = getFeedForwardTorque(dq1,dq2,q2)
%GETFEEDFORWARDTORQUE
%    OUT1 = GETFEEDFORWARDTORQUE(DQ1,DQ2,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Apr-2019 20:44:17

out1 = dq1./1.0e1-dq2.^2.*sin(q2).*(3.0./5.0e2);
