function Mmat = Mmat(q2)
%MMAT
%    MMAT = MMAT(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Apr-2019 20:44:17

t2 = cos(q2);
Mmat = reshape([3.1e1./1.0e3,t2.*(-3.0./5.0e2),t2.*(-3.0./5.0e2),3.0./1.25e2],[2,2]);
