function delta = delta(q1,q2)
%DELTA
%    DELTA = DELTA(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2019 00:10:46

t3 = q1-q2;
t2 = cos(t3);
t4 = t2.^2;
t5 = t4.*4.0;
t6 = t5-1.3e1;
t7 = 1.0./t6;
t8 = t2.*2.0;
t9 = t2.*1.5e1;
t10 = t9-5.0./4.0;
delta = reshape([t7.*t10.*(-4.0./5.0)+t7.*(t8-1.0),-t7.*(t8-1.3e1)-t2.*t7.*t10.*(8.0./5.0),t7,t2.*t7.*2.0],[2,2]);
