function output = Dine(ddq1,ddq2,dq1,dq2,q1,q2,u)
%DINE
%    OUTPUT = DINE(DDQ1,DDQ2,DQ1,DQ2,Q1,Q2,U)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2019 00:10:45

t2 = q1-q2;
t3 = sin(t2);
t4 = cos(t2);
output = [ddq1.*(6.5e1./4.0)-u-sin(q1).*1.71675e2-ddq2.*t4.*(5.0./2.0)-dq2.^2.*t3.*(5.0./2.0);ddq2.*(5.0./4.0)+u+sin(q2).*(9.81e2./4.0e1)-ddq1.*t4.*(5.0./2.0)+dq1.^2.*t3.*(5.0./2.0)];
