function gBoundaryMinus = gBoundaryMinus(dq1_minus,dq2_minus,psi,q1_minus,q2_minus)
%GBOUNDARYMINUS
%    GBOUNDARYMINUS = GBOUNDARYMINUS(DQ1_MINUS,DQ2_MINUS,PSI,Q1_MINUS,Q2_MINUS)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Mar-2019 15:39:16

t2 = psi+q1_minus;
t3 = psi+q2_minus;
t4 = sin(t2);
t5 = sin(t3);
gBoundaryMinus = reshape([-t4,0.0,-dq1_minus.*cos(t2),-cos(q1_minus),t5,0.0,dq2_minus.*cos(t3),cos(q2_minus),0.0,0.0,-t4,0.0,0.0,0.0,t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,7]);
