function gOutput = gDine(ddq1,ddq2,dq1,dq2,q1,q2)
%GDINE
%    GOUTPUT = GDINE(DDQ1,DDQ2,DQ1,DQ2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2019 00:10:45

t2 = q1-q2;
t3 = dq2.^2;
t4 = cos(t2);
t5 = sin(t2);
t6 = ddq2.*t5.*(5.0./2.0);
t7 = dq1.^2;
t8 = t4.*t7.*(5.0./2.0);
t9 = ddq1.*t5.*(5.0./2.0);
gOutput = reshape([t6-cos(q1).*1.71675e2-t3.*t4.*(5.0./2.0),t8+t9,-t6+t3.*t4.*(5.0./2.0),-t8-t9+cos(q2).*(9.81e2./4.0e1),0.0,dq1.*t5.*5.0,dq2.*t5.*-5.0,0.0,6.5e1./4.0,t4.*(-5.0./2.0),t4.*(-5.0./2.0),5.0./4.0,-1.0,1.0],[2,7]);
