function gImpactOutputPlus = gImpactPlus
%GIMPACTPLUS
%    GIMPACTOUTPUTPLUS = GIMPACTPLUS

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2019 00:10:46

gImpactOutputPlus = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
