function gImpactOutputMinus = gImpactMinus(dq1,dq2,q1,q2)
%GIMPACTMINUS
%    GIMPACTOUTPUTMINUS = GIMPACTMINUS(DQ1,DQ2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2019 00:10:46

t2 = q1-q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.^2;
t6 = t5.*4.0;
t7 = t6-1.3e1;
t8 = 1.0./t7.^2;
t9 = 1.0./t7;
t10 = t4.*t9.*1.0e1;
t11 = t3.*2.0;
t12 = t11-1.0;
t13 = t3.*t4.*t8.*t12.*8.0;
t14 = t3.*1.5e1;
t15 = t14-5.0./4.0;
t16 = t10+t13-t3.*t4.*t8.*t15.*(3.2e1./5.0);
t17 = t4.*t9.*2.0;
t18 = t4.*t9.*t15.*(8.0./5.0);
t19 = t3.*t4.*t9.*2.4e1;
t20 = t11-1.3e1;
t21 = t17+t18+t19-t4.*t5.*t8.*t15.*(6.4e1./5.0)-t3.*t4.*t8.*t20.*8.0;
t22 = dq2.*t4.*t9.*2.0;
gImpactOutputMinus = reshape([-dq1.*t16-dq2.*t3.*t4.*t8.*8.0,t22-dq1.*t21-dq2.*t4.*t5.*t8.*1.6e1,dq1.*t16+dq2.*t3.*t4.*t8.*8.0,-t22+dq1.*t21+dq2.*t4.*t5.*t8.*1.6e1,-t9.*t12+t9.*t15.*(4.0./5.0),t9.*t20+t3.*t9.*t15.*(8.0./5.0),-t9,t3.*t9.*-2.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
